### ISSUE TITLE
Passing dataset to datatable

### ISSUE THREAD

**Issue by JonathanShrek** [JustinWilkinson/DataTables.Blazor#12]
Is it possible to pass in a dataset to the datatable? I haven't figured out a way to do this and am not sure if this is a feature.

**Comment by JustinWilkinson** [comment]
The table component can be DOM sourced or it can pick up its data from the Source URL.
If you're wanting to set the data for the table component from an `IEnumerable<T>` or `object[]` I don't think I've added support for that yet as it's not something I've used myself. That said I think it should be straightforward to add.

**Comment by JonathanShrek** [comment]
Yeah it would be a nice feature if I could pass an object of data to the datatable kind of like this
```
Object dataset = GetData();

<DataTable data="dataset">
    ...
    ...
</DataTable>
```
Currently, I have a component that passes data to a js function that does this, but it would be nice to get away from this and use your package.

**Comment by JustinWilkinson** [comment]
Hi Jonathan - having refreshed myself on this, it seems this behaviour is already possible when using the `DataTableOptions.Data` property.
That said, in an attempt to improve type safety (at least within the list of objects), and usability I've added a `Dataset<T>` class, and a property on the `DataTable` component in https://github.com/JustinWilkinson/DataTables.Blazor/pull/13.
I've updated the demo to show the usage but it's worth noting that at the moment you'll need to adjust the casing of the `Column.Data` property yourself to ensure it matches post serialization.
```
public record RowObject
{
	public Column1 { get; init; }
	
	public Column2 { get; init; }
	
	public Column3 { get; init; }
}

var lst = GetSomeList<RowObject>();
var dataset = new Dataset<RowObject>(lst);

<DataTable Id="MyObjectSourceData" Class="table table-striped table-bordered w-100" Data=dataset>
	<Column Title="Column 1" Data="column1" />
	<Column Title="Column 2" Data="column2" />
	<Column Title="Column 3" Data="column3" />
</DataTable>
```
