### ISSUE TITLE
Ambiguous reference between DataTables.Blazor.Column and Bootstrap Blazor component libraries

### ISSUE THREAD

**Issue by soenneker** [JustinWilkinson/DataTables.Blazor#14]
You may want to rename your "Column" component to "DTColumn" or something like that, otherwise if people are using other libraries that have a Column component (i.e. Blazorise, etc) they'll get an ambiguous error like:

![image](https://user-images.githubusercontent.com/4441470/150207898-46b3c098-6a5b-4b57-9bb1-d34e09a2d8f6.png)

![image](https://user-images.githubusercontent.com/4441470/150208303-4d2e6d76-b9d6-4e7e-8f48-9622fbd15d70.png)

Obviously one can specify the type further (`Blazorise.Column`, `DataTables.Blazor.Column`), but perhaps that's not the best experience.

Thanks for the component library!

**Comment by JustinWilkinson** [comment]
I'd thought this earlier today. One day MSFT will implement aliasing for components...
As there seem to be a few users now it might be worth doing.

**Comment by JustinWilkinson** [comment]
@soenneker - if you update to version 3.0.0 of the library created in https://github.com/JustinWilkinson/DataTables.Blazor/pull/15 I have renamed the `Column` component `DataTableColumn`.
Hopefully this will reduce the risk of naming clashes for you 😄

**Comment by soenneker** [comment]
Thank you! Much appreciated. I completely agree about the blazor alias issue.

https://github.com/dotnet/razor-tooling/issues/7670
