### ISSUE TITLE
Upgrade to Datatables 1.10.24

### ISSUE THREAD

**Issue by timlarson345** [JustinWilkinson/DataTables.Blazor#2]
Do you mind if I do an upgrade of Datatables to 1.10.24?  I'll be glad to put together a PR for it.

I've been looking for a way to integrate DataTables with Blazor, and this project lines up with how I'd like to do the integration.  I'd like to help out and contribute to this project, if you're open to it.

**Comment by JustinWilkinson** [comment]
I haven't really looked at this recently, but I don't think there's anything stopping you from using whatever version of DataTables you like with this.
That said, the version in the demo could be bumped and any new options in DataTables 1.10.24 that you want to use might need adding - if there's anything you want to do, feel free to create a PR.

**Comment by timlarson345** [comment]
Fixed with #3
