### ISSUE TITLE
Can I add a button to the DataTableColumn content?

### ISSUE THREAD

**Issue by mummyildiz** [JustinWilkinson/DataTables.Blazor#26]
Hi,
Thank you for the component.
Can I add a button to the DataTableColumn content?

**Comment by soenneker** [comment]
You can add any type of html content you wish. This would typically be done via markup though (and simply initializing DataTables in code), not via data injection.

**Comment by mummyildiz** [comment]
can we use it like this?

`<DataTableColumn Title="Total" Data="total" DefaultContent="-" >    
        <button class="btn btn-warning" @onclick="() => OkunduIsaretle(item.Id)">@(item.Flag.Equals(1) ? item.FlagAdi : 
                      "Okundu işaretle")</button>    
</DataTableColumn>`

**Comment by soenneker** [comment]
Just do something like this:
```html
<DataTable>
    <thead>
        <tr>
            <th>Button</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                <button class="btn btn-warning" @onclick="() => OkunduIsaretle(item.Id)">@(item.Flag.Equals(1) ?
                    item.FlagAdi : "Okundu işaretle")</button>
            </td>
        </tr>
    </tbody>
</DataTable>
```
