### ISSUE TITLE
C# data source collection, datatable

### ISSUE THREAD

**Issue by thenhthang** [JustinWilkinson/DataTables.Blazor#29]
How to set DataSource with List, Datatable

**Comment by abberdeen** [comment]
`<DataTable Id="MyObjectSourceData" Class="table table-striped table-bordered w-100" Data=WeatherDataset>`
....

https://github.com/JustinWilkinson/DataTables.Blazor/blob/e564b79a530d04dbea7887b05f6d1ef1c0eedf76/DataTables.Blazor.Demo/Pages/Index.razor#L158C117-L158C136
